name: SampleWorkflow
on: 
  push: 
    branches:  [main]
jobs: 
  Check: 
    name: Check
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    timeout-minutes: 10
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Check
      id: check-paclet-step
      uses: rhennigan/check-paclet@v1.4.0
      with: 
        target: Submit
        paclet_cicd_version: 0.7.0
        definition_notebook: ./DefinitionNotebook.nb
  Compile-Linux-x86-64: 
    name: Compile-Linux-x86-64
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Compile
      run: wolframscript Scripts/Compile.wls
    - with: 
        path: LibraryResources/Linux-x86-64
        if-no-files-found: error
        name: Linux-x86-64
      name: Upload
      id: upload-artifacts-step
      uses: actions/upload-artifact@v2
    needs:  [Check]
  Compile-Windows-x86-64: 
    name: Compile-Windows-x86-64
    runs-on: windows-latest
    env: 
      WOLFRAM_SYSTEM_ID: Windows-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
      WOLFRAMENGINE_INSTALL_MSI_DOWNLOAD_URL: https://files.wolframcdn.com/packages/winget/13.0.0.0/WolframEngine_13.0.0_WIN.msi
      WOLFRAMENGINE_CACHE_KEY: WolframEngine-A
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Compile
      run: |
        $env:Path += ';${{ env.WOLFRAMENGINE_INSTALLATION_DIRECTORY }}\'
        wolfram -script Scripts/Compile.wls
      env: 
        WOLFRAMENGINE_INSTALLATION_DIRECTORY: '${{ runner.temp }}\WolframEngine'
        WOLFRAMINIT: "-pwfile !cloudlm.wolfram.com -entitlement ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}"
    - with: 
        path: LibraryResources/Windows-x86-64
        if-no-files-found: error
        name: Windows-x86-64
      name: Upload
      id: upload-artifacts-step
      uses: actions/upload-artifact@v2
    needs:  [Check]
  Compile-MacOSX-x86-64: 
    name: Compile-MacOSX-x86-64
    runs-on: macos-latest
    env: 
      WOLFRAM_SYSTEM_ID: MacOSX-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
      WOLFRAMENGINE_CACHE_KEY: WolframEngine-A
      WOLFRAMENGINE_INSTALLATION_DIRECTORY: "/Applications/Wolfram Engine.app"
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Compile
      run: |
        export PATH="${{ env.WOLFRAMENGINE_EXECUTABLES_DIRECTORY }}:$PATH"
        wolframscript -debug -verbose -script Scripts/Compile.wls
      env: 
        WOLFRAMENGINE_EXECUTABLES_DIRECTORY: "${{ env.WOLFRAMENGINE_INSTALLATION_DIRECTORY }}/Contents/Resources/Wolfram Player.app/Contents/MacOS"
        WOLFRAMSCRIPT_KERNELPATH: "${{ env.WOLFRAMENGINE_INSTALLATION_DIRECTORY }}/Contents/MacOS/WolframKernel"
    - with: 
        path: LibraryResources/MacOSX-x86-64
        if-no-files-found: error
        name: MacOSX-x86-64
      name: Upload
      id: upload-artifacts-step
      uses: actions/upload-artifact@v2
    needs:  [Check]
  TestPaclet: 
    name: TestPaclet
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - with: 
        path: LibraryResources
      name: Download
      id: download-artifacts-step
      uses: actions/download-artifact@v2
    - name: Test
      id: test-paclet-step
      uses: rhennigan/test-paclet@v1.0.0
      with: 
        target: Submit
        paclet_cicd_version: 0.7.0
        definition_notebook: ./DefinitionNotebook.nb
    needs: 
    - Compile-Linux-x86-64
    - Compile-Windows-x86-64
    - Compile-MacOSX-x86-64
    - Check
  BuildPaclet: 
    name: BuildPaclet
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - with: 
        path: LibraryResources
      name: Download
      id: download-artifacts-step
      uses: actions/download-artifact@v2
    - name: SetBuildDate
      run: wolframscript Scripts/SetBuildDate.wls
    - name: Build
      id: build-paclet-step
      uses: rhennigan/build-paclet@v1.4.0
      with: 
        target: Submit
        paclet_cicd_version: 0.7.0
        definition_notebook: ./DefinitionNotebook.nb
    - with: 
        path: build
        if-no-files-found: error
      name: Upload
      id: upload-artifacts-step
      uses: actions/upload-artifact@v2
    needs: 
    - Compile-Linux-x86-64
    - Compile-Windows-x86-64
    - Compile-MacOSX-x86-64
    - Check
    - TestPaclet